ARG opensearch_version=2.7.0

FROM opensearchproject/opensearch:${opensearch_version}
ARG opensearch_version=2.7.0

# todo: LTR
#ARG ltrversion=2.1.0
#RUN /usr/share/opensearch/bin/opensearch-plugin install -b https://github.com/gsingers/opensearch-learning-to-rank-base/releases/download/release-v${ltrversion}/ltr-plugin-v${ltrversion}.zip

# todo: Querqy
# RUN /usr/share/opensearch/bin/opensearch-plugin install -b "url"