FROM opensearchproject/opensearch:2.19.1

# todo: Querqy
#COPY opensearch-querqy-1.0.os2.7.0-SNAPSHOT.zip /tmp/
#RUN /usr/share/opensearch/bin/opensearch-plugin install -b "file:///tmp/opensearch-querqy-1.0.os2.7.0-SNAPSHOT.zip"