services:

  os-tmdb-node:
    build: os-docker/.
    container_name: os-tmdb-node
    environment:
      cluster.name: opensearch-cluster
      node.name: os-tmdb-node
      discovery.type: single-node
      http.cors.enabled: true
      http.cors.allow-origin: "*"
      http.cors.allow-methods: OPTIONS,HEAD,GET,POST,PUT,DELETE
      http.cors.allow-headers: X-Requested-With,X-Auth-Token,Content-Type,Content-Length,Authorization,test,access-control-allow-headers,x-search-query,X-Search-Id,X-Search-Filters,X-ubi-query-id,X-ubi-store,X-ubi-user-id,X-ubi-session-id,x-search-client,Access-Control-Expose-Headers
      http.cors.allow-credentials: true
      OPENSEARCH_JAVA_OPTS: -Xms1g -Xmx4g
      plugins.security.disabled: true
      OPENSEARCH_INITIAL_ADMIN_PASSWORD: Mysupersecretpassword_123
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      - opensearch-data:/usr/share/opensearch/data
    ports:
      - "9200:9200"
      - "9600:9600"
    networks:
      - opensearch-net

  os-tmdb-dashboards:
    image: opensearchproject/opensearch-dashboards:2.19.1
    container_name: os-tmdb-dashboards
    ports:
      - "5601:5601"
    environment:
      - 'OPENSEARCH_HOSTS=["http://os-tmdb-node:9200"]'
      - "DISABLE_SECURITY_DASHBOARDS_PLUGIN=true"
    networks:
      - opensearch-net

volumes:
  opensearch-data:

networks:
  opensearch-net: